Update to Fabric 1.21
infernalstudios/Elytra-Bounce pull request #7
Opened 2024-07-10 18:13 UTC by Soumeh

- Fabric (i think) supports Quilt too, so the mod can be used on both loaders.
- Will (probably) support [Sinytra Connector](https://modrinth.com/mod/connector/versions) whenever it updates.
- Maybe works with other Minecraft versions? I removed any mc version limitations but i'm not sure how the fabric loader will handle the mod.

2024-07-10 21:25 UTC, SwanX1 commented
Please make the PR merge into the `1.19-quilt` branch, otherwise the code diff is unreadable...

2024-07-10 22:03 UTC, Soumeh commented
ah my bad, i changed it now

2024-07-14 18:16 UTC, SwanX1 requested changes
few minor changes

2024-07-14 18:16 UTC, SwanX1 commented on .editorconfig
please keep this file

2024-07-14 18:16 UTC, SwanX1 commented on gradle.properties
> +mod_version=1.1.0
no need to increment the version, if you're just porting

2024-07-14 18:16 UTC, SwanX1 commented on src/main/resources/assets/elytrabounce/META-INF/mods.toml
???

2024-07-14 20:07 UTC, SwanX1 approved these changes

2024-07-14 20:10 UTC, SwanX1 commented
Merged into new branch `fabric-1.21`

2024-07-14 20:10 UTC, closed without merging